### ISSUE TITLE
[圖片快取套件] INTERVENTION/IMAGECACHE

### ISSUE THREAD

**Issue by jjjj4564** [DaydreamLab/cms#20]
為了要讓pagespeed tool分數好看所以要使用瀏覽器快取功能
Cache-Control

https://dustinhsiao21.com/2018/01/17/laravel-%E5%9C%96%E7%89%87%E5%BF%AB%E5%8F%96%E5%A5%97%E4%BB%B6%EF%BC%9Aintervention-imagecache/

**Comment by littlegreening** [comment]
https://dsgn.tw/archives/64133/
