### ISSUE TITLE
[News] 要能篩出單一月份資料

### ISSUE THREAD

**Issue by jjjj4564** [DaydreamLab/cms#26]

**Comment by ppuff1988** [comment]
https://identity.getpostman.com/handover/multifactor?user=2664518&handover_token=21bffd80-5106-4355-8d4c-6802a40b1d55

**Comment by jjjj4564** [comment]
month 要搜尋的 key 是 publish_up 不是 created_at

**Comment by jjjj4564** [comment]
要搜尋的是 publish_up 不是 created_at

**Comment by jjjj4564** [comment]
有需要做page嗎

**Comment by ppuff1988** [comment]
> 有需要做page嗎

你是說分頁嗎？

**Comment by ppuff1988** [comment]
> 時間要搜尋的是 publish_up 不是 created_at

已更新 ，請composer update

**Comment by jjjj4564** [comment]
加page參數會搜出奶茶
